Add 3P button support to EA API and improvements
subscriptions-project/swg-js pull request #2281
Opened 2022-05-10 10:41 UTC by ed-bird

- Add native 3P button & authorizationUrl to init function
- Rename clientId with googleApiClientId
- Create promise to wait for window load
- Use existing methods instead of duplicating code
- Avoid duplicate tests by moving some from show to render_

2022-05-10 21:09 UTC, adolgachev requested changes

2022-05-11 10:08 UTC, ed-bird commented on src/utils/gaa.js
> +    const styleEl = self.document.createElement('style');
Done!

2022-05-11 10:08 UTC, ed-bird commented on src/utils/gaa.js
> +    const buttonEl = self.document.createElement('div');
Done!

2022-05-11 17:35 UTC, adolgachev approved these changes

2022-05-11 17:35 UTC, merged