Sync proto with g3 to include url_from_markup AnalyticsContext field
subscriptions-project/swg-js pull request #3571
Opened 2024-09-19 19:27 UTC by caroljli

This will be used to log the `canonicalRef` tag from markup to investigate why we have mismatching impressions logged for domains that don't belong to the publication.

2024-09-19 19:29 UTC, mhkawano approved these changes

2024-09-20 15:45 UTC, mhkawano requested changes

2024-09-20 15:45 UTC, mhkawano commented on test/e2e/vrt/baseline/chrome_mac/extendedAccess/regwall_all_experiments_on.png
This screenshot looks incorrect. Also, we haven't saved chrome_mac goldens in the past, so if you want to can we split it into a different PR?

2024-09-20 15:59 UTC, caroljli commented on test/e2e/vrt/baseline/chrome_mac/extendedAccess/regwall_all_experiments_on.png
yeah... it seemed to auto add when i was running the integration tests locally. let me remove them

2024-09-20 19:53 UTC, mhkawano approved these changes

2024-09-20 19:53 UTC, merged